define

    ruc sub attribute,
        datatype string;

    about sub attribute,
        datatype string;

    location sub attribute,
        datatype string;
    
    name sub attribute,
        datatype string;

    creationDate sub attribute,
        datatype string;
    
    dni sub attribute,
        datatype string;

    championshipWon sub attribute,
        datatype string;

    birdhdate sub attribute,
        datatype string;

    yearsExperience sub attribute,
        datatype string;

    duration sub attribute,
        datatype string;

    sessionDate sub attribute,
        datatype string;

    cost sub attribute,
        datatype string;

    maxStudents sub attribute,
        datatype string;

    minStudents sub attribute,
        datatype string;
    
    maxTickets sub attribute,
        datatype string;

    email sub attribute,
        datatype string;

    password sub attribute,
        datatype string;

    disciplines sub attribute,
        datatype string;

    title sub attribute,
        datatype string;
    
    schedule sub attribute,
        datatype string;

    traineDni sub attribute,
        datatype string;

    studentsInfo sub attribute,
        datatype string;

    studentDNI sub attribute,
        datatype string;

    email sub attribute,
        datatype string;
    
    password sub attribute,
        datatype string;


        
    school sub entity,
        has traineDni,
        has studentDNI,
        has studentsInfo,
        has location,
        has ruc,
        has about,
        has name,
        has email,
        has password,
        plays creator;
    
    trainers sub entity,
        has traineDni,
        has dni,
        has about,
        has name,
        has email,
        has password,
        has yearsExperience,
        has championshipWon;

    personalSession sub entity,
        has traineDni,
        has studentDNI,
        has studentsInfo,
        has location,
        has schedule,
        has duration,
        has cost,
        plays creating;

    schoolSession sub entity,
        has traineDni,
        has studentDNI,
        has studentsInfo,
        has location,
        has schedule,
        has duration,
        has maxStudents,
        has minStudents,
        has cost,
        plays creating;
    

    events sub entity,
        has traineDni,
        has location,
        has title,
        has schedule,
        has cost,
        plays creating;

    
    students sub entity,
        has studentDNI,
        has studentsInfo,
        has name,
        has birdhdate,
        has email,
        has password;


    create sub relation,
        relates creator,
        relates creating;

commit

