define

    willCreate sub relation,
        relates want,
        relates a,
        has name;

    school sub entity,
        key ruc,
        has about,
        has web-page,
        has location,
        has credentials,
        has trainers,
        has name,
        has students,
        has creationDate,
        has disciplines,
        plays want;
    
    trainers sub entity,
        key dni,
        has championshipWon,
        has students,
        has name,
        has birdhdate,
        has creationDate,
        has disciplines,
        has yearsExperience,
        plays want;

    personalSession sub entity,
        key trainers,
        has sessionDate,
        has duration,
        has cost,
        has location,
        has students,
        has disciplines,
        plays a;

    schoolSession sub entity,
        has school,
        has trainers,
        has students,
        has cost,
        has duration,
        has schedule,
        has maxStudents,
        has minStudents,
        has location,
        plays a;

    events sub entity,
        has cost,
        has maxTickets,
        has school,
        has title,
        has sessionDate,
        has location,
        has trainers,
        plays a;

    credentials sub entity,
        key email,
        has password;

    user sub entity,
        has name,
        has credentials,
        has creationDate,
        plays trainers,
        plays students;


    ruc sub attribute,
        datatype string;

    about sub attribute,
        datatype string;
    
    web-page sub attribute,
        datatype string;

    location sub attribute,
        datatype string;
    
    name sub attribute,
        datatype string;

    creationDate sub attribute,
        datatype date;
    
    dni sub attribute,
        datatype string;

    championshipWon sub attribute,
        datatype long;

    birdhdate sub attribute,
        datatype date;

    yearsExperience sub attribute,
        datatype long;

    duration sub attribute,
        datatype long;

    sessionDate sub attribute,
        datatype date;

    cost sub attribute,
        datatype long;

    maxStudents sub attribute,
        datatype long;

    minStudents sub attribute,
        datatype long;
    
    maxTickets sub attribute,
        datatype long;

    email sub attribute,
        datatype string;

    password sub attribute,
        datatype string;

    disciplines sub attribute,
        datatype string;

    
    

    
    

