define

    ruc sub attribute,
        datatype string;

    about sub attribute,
        datatype string;

    location sub attribute,
        datatype string;
    
    name sub attribute,
        datatype string;

    creationDate sub attribute,
        datatype date;
    
    dni sub attribute,
        datatype string;

    championshipWon sub attribute,
        datatype long;

    birdhdate sub attribute,
        datatype date;

    yearsExperience sub attribute,
        datatype long;

    duration sub attribute,
        datatype long;

    sessionDate sub attribute,
        datatype date;

    cost sub attribute,
        datatype long;

    maxStudents sub attribute,
        datatype long;

    minStudents sub attribute,
        datatype long;
    
    maxTickets sub attribute,
        datatype long;

    email sub attribute,
        datatype string;

    password sub attribute,
        datatype string;

    disciplines sub attribute,
        datatype string;

    title sub attribute,
        datatype string;
    
    schedule sub attribute,
        datatype string;

    traineDni sub attribute,
        datatype string;

    studentsInfo sub attribute,
        datatype string;
    credentials sub entity,
        has email,
        has password;


        
    school sub entity,
        has traineDni,
        has studentDNI,
        has studentsInfo,
        has location,
        has ruc,
        has about,
        has name,
        has credentials,
        plays creator;
    
    trainers sub entity,
        has traineDni,
        has dni,
        has about,
        has name,
        has credentials,
        has yearsExperience,
        has championshipWon,
        plays creator;

    personalSession sub entity,
        has traineDni,
        has studentDNI,
        has studentsInfo,
        has location,
        has schedule,
        has duration,
        has cost,
        plays creating;

    schoolSession sub entity,
        has traineDni,
        has studentDNI,
        has studentsInfo,
        has location,
        has maxStudents,
        has minStudents,
        has duration,
        has schedule,
        has cost,
        plays creating;
    

    events sub entity,
        has traineDni,
        has studentDNI,
        has studentsInfo,
        has location,
        has maxStudents,
        has minStudents,
        has title,
        has schedule,
        has cost,
        plays creating;

    
    students sub entity,
        has studentDNI,
        has studentsInfo,
        has name,
        has birdhdate,
        has credentials;


    create sub relation,
        relates creator,
        relates creating;